exercise_app/models.py
from exercise_app import db
from sqlalchemy.orm import backref
from flask_login import UserMixin

class Exercise(db.Model):
    '''Exercise model'''
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(80), nullable = False)
    description = db.Column(db.String(300), nullable = False)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable = False)
    category = db.relationship('Category', back_populates='exercises')
    favorited_by = db.relationship('User', secondary='favorite_exercises_table', back_populates='favorite_exercises')

    def __str__(self):
        return f'{self.name}'

class Category(db.Model):
    '''Category model'''
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(80), nullable = False)
    exercises = db.relationship('Exercise', back_populates='category')

    def __str__(self):
        return f'{self.name}'

class User(UserMixin, db.Model):
    '''User model'''
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    favorite_exercises = db.relationship('Exercise', secondary='favorite_exercises_table', back_populates='favorited_by')

    def __str__(self):
        return f'{self.username}'
        
favorite_user_exercises = db.Table('favorite_exercises_table', 
    db.Column('exercise_id', db.Integer, db.ForeignKey('exercise.id')),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'))
)

exercise_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, DateField, SelectField, SubmitField, TextAreaField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, ValidationError
from exercise_app.models import Category, Exercise

class ExerciseForm(FlaskForm):
    '''Exercise creation form'''
    name = StringField('Exercise Name', validators=[DataRequired(), Length(min=3, max=100)])
    description = StringField('Brief Description', validators=[DataRequired(), Length(min=3, max=300)])
    category = QuerySelectField('Category', query_factory=lambda: Category.query, allow_blank=False)
    submit = SubmitField('Submit')

class CategoryForm(FlaskForm):
    '''Category creation form'''
    name = StringField('Category Name', validators=[DataRequired(), Length(min=3, max=100)])
    submit = SubmitField('Submit')

exercise_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from exercise_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)

db = SQLAlchemy(app)

# Authentication

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.init_app(app)

from .models import User

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)

bcrypt = Bcrypt(app)

# Blueprints

from exercise_app.main.routes import main as main_routes
app.register_blueprint(main_routes)

from exercise_app.auth.routes import auth as auth_routes
app.register_blueprint(auth_routes)

with app.app_context():
    db.create_all()

exercise_app/main/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from exercise_app.models import Category, Exercise, User
from exercise_app.main.forms import ExerciseForm, CategoryForm
from exercise_app import bcrypt
from exercise_app import app, db

main = Blueprint('main', __name__)

# Routes

@main.route('/')
def homepage():
    all_categories = Category.query.all()
    all_exercises = Exercise.query.all()

    return render_template('homepage.html', all_categories=all_categories, all_exercises=all_exercises)

@main.route('/create_category', methods=['POST', 'GET'])
@login_required
def create_category():
    form = CategoryForm()

    if form.validate_on_submit():
        new_category = Category(
            name = form.name.data
        )
        db.session.add(new_category)
        db.session.commit()

        flash('New category was added')
        return redirect(url_for('main.category_detail', category_id=new_category.id))
    return render_template('/create_category.html', form=form)

@main.route('/category/<category_id>', methods=['POST', 'GET'])
def category_detail(category_id):
    category = Category.query.filter_by(id=category_id).one()
    exercises_in_cat = category.exercises
    form = CategoryForm(obj=category)

    if form.validate_on_submit():
        category.name = form.name.data

        db.session.commit()
        flash('Category name updated')
        return redirect(url_for('main.category_detail', category_id=category_id))
    return render_template('category_detail.html', category=category, form=form, exercises=exercises_in_cat)

@main.route('/create_exercise', methods=['POST', 'GET'])
@login_required
def create_exercise():
    form = ExerciseForm()

    if form.validate_on_submit():
        new_exercise = Exercise(
            name = form.name.data,
            description = form.description.data,
            category = form.category.data
        )
        db.session.add(new_exercise)
        db.session.commit()

        flash('New exercise added')
        return redirect(url_for('main.exercise_detail', exercise_id=new_exercise.id))
    return render_template('create_exercise.html', form=form)

@main.route('/exercise/<exercise_id>', methods=['POST', 'GET'])
def exercise_detail(exercise_id):
    exercise = Exercise.query.filter_by(id=exercise_id).one()
    form = ExerciseForm(obj=exercise)

    if form.validate_on_submit():
        exercise.name = form.name.data
        exercise.description = form.description.data
        exercise.category = form.category.data

        db.session.commit()
        flash('Exercise updated')
        return redirect(url_for('main.exercise_detail', exercise_id=exercise_id))
    return render_template('exercise_detail.html', exercise=exercise, form=form)

@main.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).one()
    return render_template('profile.html', user=user)

@main.route('/favorite/<exercise_id>', methods=['POST'])
@login_required
def favorite(exercise_id):
    exercise = Exercise.query.filter_by(id=exercise_id).one()
    if exercise in current_user.favorite_exercises:
        flash(f'{exercise.name} already in your favorites.')
    else:
        current_user.favorite_exercises.append(exercise)
        db.session.add(current_user)
        db.session.commit()
        flash(f'{exercise.name} added to your favorites.')
    return redirect(url_for('main.exercise_detail', exercise_id=exercise_id))

@main.route('/unfavorite/<exercise_id>', methods=['POST'])
@login_required
def unfavorite(exercise_id):
    exercise = Exercise.query.filter_by(id=exercise_id).one()
    if exercise not in current_user.favorite_exercises:
        flash(f'{exercise.name} not in your favorites. Add it first.')
    else:
        current_user.favorite_exercises.remove(exercise)
        db.session.add(current_user)
        db.session.commit()
        flash(f'{exercise.name} removed from your favorites.')
    return redirect(url_for('main.exercise_detail', exercise_id=exercise_id))

@main.route('/delete_category/<category_id>', methods=['POST'])
@login_required
def delete_category(category_id):
    Category.query.filter_by(id=category_id).delete()

    db.session.commit()
    return redirect(url_for('main.homepage'))

@main.route('/delete_exercise/<exercise_id>', methods=['POST'])
@login_required
def delete_exercise(exercise_id):
    Exercise.query.filter_by(id=exercise_id).delete()

    db.session.commit()
    return redirect(url_for('main.homepage'))

exercise_app/templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <title>Exercise Database</title>
    </head>
    <body>
        <nav>
            <a href='/'>Homepage</a>

            {% if current_user.is_authenticated %}
            <a href='/create_exercise'>Create Exercise</a>
            <a href='/create_category'>Create Category</a>
            <a href='/profile/{{ current_user.username }}'>{{ current_user.username }}'s profile</a>
            <a href='/logout'>Log Out</a>
            <p>Welcome, {{ current_user.username }}.</p>
            {% else %}
            <a href='/signup'>Sign Up</a>
            <a href='/login'>Log In</a>
            <p>You must be logged in to create exercises and categories</p>
            {% endif %}
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

exercise_app/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ category.name }}</h1>

<p>Exercises in this category:</p>
<ul>
    {% for exercise in exercises %}
    <li>{{ exercise.name }}</li>
    {% endfor %}
</ul>

<form method="POST" action="{{ url_for('main.category_detail', category_id=category.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit category name</legend>

        {{ form.name.label }}
        {{ form.name }}

        {{ form.submit }}
    </fieldset>
</form>

<form method='POST' action='/delete_category/{{ category.id }}'>
    <input type='submit' value='Delete category'>
</form>

{% endblock %}

exercise_app/templates/create_category.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_category')}}">
    {{ form.csrf_token }}

    <fieldset>
        <legend>Enter a new category</legend>

        {{ form.name.label }}
        {{ form.name }}
        <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>        

        {{ form.submit }}
    </fieldset>
</form>
{% endblock %}

exercise_app/templates/create_exercise.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('main.create_exercise') }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter a new exercise</legend>
        {{ form.name.label }}
        {{ form.name }}
        <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.description.label }}
        {{ form.description }}
        <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        
        {{ form.category.label }}
        {{ form.category }}
        <ul>
            {% for error in form.category.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}

</form>
{% endblock %}

exercise_app/templates/exercise_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ exercise.name }}</h1>

<p>Description: {{ exercise.description }}</p>
<p>Muscle group: {{ exercise.category }}</p>

{% if current_user.is_authenticated %}
    {% if exercise not in current_user.favorite_exercises %}
    <form action='/favorite/{{ exercise.id }}' method='POST'>
        <input type='submit' value='Add to favorites'>
    </form>
    {% else %}
    <form action='/unfavorite/{{ exercise.id }}' method='POST'>
        <input type='submit' value='Remove from favorites'>
    </form>
    {% endif %}
{% endif %}

<form method='POST' action="{{ url_for('main.exercise_detail', exercise_id=exercise.id) }}">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Edit exercise</legend>
        {{ form.name.label }}
        {{ form.name }}
        <ul>
            {% for error in form.name.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.description.label }}
        {{ form.description }}
        <ul>
            {% for error in form.description.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        
        {{ form.category.label }}
        {{ form.category }}
        <ul>
            {% for error in form.category.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

<form method='POST' action='/delete_exercise/{{ exercise.id }}'>
    <input type='submit' value='Delete exercise'>
</form>
{% endblock %}

exercise_app/templates/homepage.html
{% extends 'base.html' %}

{% block content %}

<h3>Categories</h3>
<ol>
    {% for category in all_categories %}
    <li><a href="/category/{{ category.id }}">{{ category.name }}</a></li>
    {% endfor %}
</ol>

<h3>Exercises</h3>
<ol>
    {% for exercise in all_exercises %}
    <li><a href="/exercise/{{ exercise.id }}">{{ exercise.name }}</a></li>
    {% endfor %}
</ol>

{% endblock %}

exercise_app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>Log In</h1>

<form action='/login' method='POST'>
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter information</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

exercise_app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<p>
    Your favorite exercises:

    <ul>
        {% for exercise in user.favorite_exercises %}
        <li><a href="/exercise/{{ exercise.id }}">{{ exercise.name }}</a></li>
        {% endfor %}
    </ul>
</p>

{% endblock %}

exercise_app/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>Create account</h1>

<form action='/signup' method='POST'>
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter information</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}